CREATE TABLE `farBaselineVersions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`previousCount` int NOT NULL,
	`newCount` int NOT NULL,
	`previousValue` decimal(14,2),
	`newValue` decimal(14,2),
	`reason` text NOT NULL,
	`changedBy` int NOT NULL,
	`changedByName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `farBaselineVersions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `phase2Milestones` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`milestoneNumber` int NOT NULL,
	`milestoneName` varchar(500) NOT NULL,
	`status` enum('not_started','in_progress','completed','on_hold') NOT NULL DEFAULT 'not_started',
	`completionPercent` int NOT NULL DEFAULT 0,
	`startDate` timestamp,
	`targetDate` timestamp,
	`completionDate` timestamp,
	`clientUpdate` text,
	`internalNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `phase2Milestones_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projectDepartments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`departmentName` varchar(500) NOT NULL,
	`departmentCode` varchar(100),
	`contact` varchar(255),
	`verificationStatus` enum('not_started','in_progress','completed','partial') NOT NULL DEFAULT 'not_started',
	`scheduledDate` timestamp,
	`completedDate` timestamp,
	`clientNotes` text,
	`internalNotes` text,
	`assetCount` int DEFAULT 0,
	`isClientVisible` int NOT NULL DEFAULT 1,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projectDepartments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projectLocations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`locationName` varchar(500) NOT NULL,
	`address` text,
	`siteCode` varchar(100),
	`contact` varchar(255),
	`verificationStatus` enum('not_started','in_progress','completed','partial') NOT NULL DEFAULT 'not_started',
	`scheduledDate` timestamp,
	`completedDate` timestamp,
	`clientNotes` text,
	`internalNotes` text,
	`assetCount` int DEFAULT 0,
	`isClientVisible` int NOT NULL DEFAULT 1,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projectLocations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projectVerificationMetrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`farBaselineCount` int NOT NULL DEFAULT 0,
	`farBaselineValue` decimal(14,2) DEFAULT '0',
	`verifiedFarAssets` int NOT NULL DEFAULT 0,
	`notFoundAssets` int NOT NULL DEFAULT 0,
	`additionalAssetsFound` int NOT NULL DEFAULT 0,
	`ghostAssetCount` int NOT NULL DEFAULT 0,
	`ghostAssetValue` decimal(14,2) DEFAULT '0',
	`zombieAssetCount` int NOT NULL DEFAULT 0,
	`zombieAssetValue` decimal(14,2) DEFAULT '0',
	`vampireAssetCount` int NOT NULL DEFAULT 0,
	`vampireAssetValue` decimal(14,2) DEFAULT '0',
	`duplicateAssetCount` int NOT NULL DEFAULT 0,
	`duplicateAssetValue` decimal(14,2) DEFAULT '0',
	`assetsInRepair` int NOT NULL DEFAULT 0,
	`activeAssets` int NOT NULL DEFAULT 0,
	`conditionDistribution` json,
	`ghostNotes` text,
	`zombieNotes` text,
	`vampireNotes` text,
	`duplicateNotes` text,
	`generalNotes` text,
	`phase2Status` enum('not_started','on_track','at_risk','delayed','complete') NOT NULL DEFAULT 'not_started',
	`phase2StartDate` timestamp,
	`phase2TargetDate` timestamp,
	`phase2CostBasis` decimal(14,2),
	`clientFacingSummary` text,
	`internalNotes` text,
	`lastUpdateNotes` text,
	`updatedBy` int,
	`updatedByName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projectVerificationMetrics_id` PRIMARY KEY(`id`)
);
